development:
  adapter: postgresql
  encoding: unicode
  database: overshare_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: 192.168.215.2

test:
  adapter: postgresql
  encoding: unicode
  database: overshare_test
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: 192.168.215.2

production:
  adapter: postgresql
  encoding: unicode
  database: overshare_production
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV["DB_PORT"] %>
